# Generated by Django 4.2.1 on 2023-06-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.TextField(max_length=300)),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
    ]
