# Generated by Django 4.2.1 on 2023-07-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True),
        ),
    ]
